### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [maxpolun/chum#1]
proper db equivalent for such code:

``` js
migrationHasRun (migration) {
    return this._conn.query('SELECT * FROM chum_migrations WHERE complete_migrations = $1', [migration])
    .then(results => {
      if (results.length !== 1) throw new Error('expected one row')
    })
  }
```

is this one:

``` js
migrationHasRun (migration) {
    return this._conn.one('SELECT * FROM chum_migrations WHERE complete_migrations = $1', [migration]);
  }
```

Also see [Query Files](https://github.com/vitaly-t/pg-promise#query-files) - a much better way to deal with external SQL files ;)

**Comment by maxpolun** [comment]
I tried that and wasn't getting an error. Maybe worth a shot again.

I did look at query files, but I'm not sure it's the right approach for this tool. There's essentially zero chance of a migration file being run more than once, so it's kind of pointless for this use.

**Comment by maxpolun** [comment]
#bbefaa4 fixed.

Must have been something else wrong when I tested it originally.

**Comment by vitaly-t** [comment]
> I did look at query files, but I'm not sure it's the right approach for this tool. There's essentially zero chance of a migration file being run more than once, so it's kind of pointless for this use.

It is also safer, as you can parse the SQL being loaded. And the type can be passed into query methods directly ;)
